config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  resources :articles do
  	resources :comments
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
has_many :comments, dependent: :destroy
validates :title, presence: true,
				length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

   http_basic_authenticate_with name: "Oman", password: "secret", except: [:index, :show]

  def index
  	@articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
  	@article = Article.find(params[:id])
  end

  def save
    @article = Article.new(article_params)
    if 
    @article.save
    redirect_to @article
    else
    render 'new'  
    end
  end

  def create
  	@article = Article.new(article_params)
    if 
    @article.save
    redirect_to @article
    else
    render 'new'  
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private 
  def article_params
  	params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def comments_controller
  end
	
  http_basic_authenticate_with name: "Oman", password: "secret", only: :destroy

  def create
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.create(comment_params)
  	redirect_to article_path(@article)
  end

  def destroy
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.find(params[:id])
  	@comment.destroy
  	redirect_to article_path(@article)
  end

private
  def comment_params
  	params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<h1>Articles</h1>
<%= form_with model: @article, local: true do |form|%>
<%if @article.errors.any?%>
<div id="error_explanation">
	<h2>
		<%pluralize(@article.errors.count, "error")%>
		Prohibited this article from being saved:
	</h2>
	<ul>
		<%@article.errors.full_messages.each do |msg|%>
		<li><%=msg%></li>
		<%end%>
	</ul>
</div>
<%end%>
<p>
	<%= form.label :title%><br>
	<%= form.text_field :title%>
</p>
<p>
	<%= form.label :text%><br>
	<%= form.text_area :text%>
</p>
<p>
	<%= form.submit%>
</p>
<%end%>

app/views/articles/edit.html.erb
<%= render 'form'%>
<%= link_to 'back', articles_path%>

app/views/articles/index.html.erb
<h1>Articles index</h1>
<a class="btn btn-outline-primary" href="articles/new" role="button" class="btn-btn">Add</a>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  ADD
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ADD ARTICLES</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with scope: :article, url: articles_path, local: true do |form|%>
        <p>
        	<%= form.label :title%><br>
        	<%= form.text_field :title%>
        </p>
        <p>
        	<%= form.label :text%><br>
        	<%= form.text_area :text%>
        </p>
        <p>
        	<%= form.submit%>
        </p>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<table border="1" width="40%" class="table">
	<tr>
		<th>Nama</th>
		<th>Alamat</th>
		<th colspan="3"></th>
	</tr>
	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %> </td>
		<td><%= article.text %> </td>
		<td><div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Actions
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#"><center><%=link_to'Show', article_path(article)%></center></a>
    <a class="dropdown-item" href="#"><center><%= link_to 'edit', edit_article_path(article)%></center></a>
    <a class="dropdown-item" href="#"><center><%= link_to 'hapus', article_path(article),
						method: :delete,
						data: {confirm: 'Are You Sure?'}%></center></a>
  </div>
</div></td>
	</tr>
	<%end%>
</table>

app/views/articles/new.html.erb
<%= render 'form'%>
<%= link_to 'back', articles_path%>

app/views/articles/show.html.erb
<h1>Articles show</h1>
<p>
	<strong>Nama :</strong> 
	<%= @article.title%>
</p>

<p>
	<strong>Alamat</strong>
	<%= @article.text%>
</p>
<h2>Comentar</h2>
<%= render @article.comments%>

<h2>Add a Comment:</h2>
<%= render 'comments/form'%>
<%= link_to 'edit', edit_article_path(@article)%> | 
<%= link_to 'back', articles_path%>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter</strong>
	<%= comment.commenter%>
</p>
<p>
	<strong>Comments</strong>
	<%= comment.body%>
</p>
<%= link_to 'Destroy Comment', [comment.article, comment],method: :delete, data: {confirm: 'Are You Sure?'}%>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], local: true) do |form|%>
<p>
	<%= form.label :commenter%><br>
	<%= form.text_field :commenter%>
</p>
<p>
	<%= form.label :body%><br>
	<%= form.text_area :body%>
</p>
<p>
	<%= form.submit%>
</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="contener">
    <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<%= link_to 'My_blog', controller: 'articles'%>
<a class="btn btn-outline-primary" href="../articles/" role="button" class="btn-btn">Link</a>